mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('post.urls', namespace='post')),
    url(r'^auth/', include('userauth.urls', namespace='auth')),
]

##여기서부터 튜토리얼 따라가기

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

#django.conf.urls.static.static()함수는
#첫 번째 인자로 주어진 경로(MEDIA_URL)로 요청이 올 경우,
#document_root에 지정된 경로에서 파일을 찾아 응답으로 보내준다.

mysite/post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    # url(r'^post/(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    # url(r'^post/write', views.post_create, name='post_create'),
    # url(r'^post/(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    # url(r'^(?P<post_pk>\d+)/like-toggle/$', views.post_like_toggle, name='post_like_toggle'),
# legacy ends here
    url(r'^oe/list/$', views.oe_haters_list, name='oe_haters_list'),
    url(r'^oe/list/byp/(?P<provider_pk>\d+)/', views.oe_haters_list_byprovider, name='oe_haters_list_byprovider'),
    url(r'^oe/list/bys/$', views.oe_haters_list_byscore, name='oe_haters_list_byscore'),

    url(r'^oe/ranking/(?P<order>\w+)/(?P<page_num>\d+)$', views.oe_haters_ranking, name='oe_haters_ranking'),

    url(r'^oe/(?P<food_pk>\d+)/$', views.oe_haters_detail, name='oe_haters_detail'),
    url(r'^oe/(?P<food_pk>\d+)/hate-toggle/$', views.oe_haters_hate_toggle, name='oe_haters_hate_toggle'),
    url(r'^oe/(?P<food_pk>\d+)/like-toggle/$', views.oe_haters_like_toggle, name='oe_haters_like_toggle'),
    url(r'^oe/(?P<food_pk>\d+)/food/comment/create/$', views.oe_food_comment_create, name='oe_food_comment_create'),
]

mysite/userauth/urls.py
from django.conf.urls import url

from . import views
app_name="member"
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport"
	      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="{% static 'css/style.css' %}?ver=4">
	<link href="https://fonts.googleapis.com/css?family=Nanum+Gothic|Noto+Sans+KR:700" rel="stylesheet">
	{% block head %}
	{% endblock %}
	<title>오지랖ing</title>
</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNavDropdown">
		    <ul class="navbar-nav">
				<li class="nav-item active">
				  <a class="nav-link" href="{% url 'post:oe_haters_list' %}">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item active">
				  <a class="nav-link" href="{% url 'post:oe_haters_list' %}">전체목록 <span class="sr-only">(current)</span></a>
				</li>
				{% if user.is_authenticated %}
  				  <li class="nav-item">
  				    <a class="nav-link" href="{% url 'member:logout' %}">Logout</a>
  				  </li>
  			  {% else %}
  				  <li class="nav-item">
  					<a class="nav-link" href="{% url 'member:login' %}">Login</a>
  				  </li>
  				  <li class="nav-item">
  					<a class="nav-link" href="{% url 'member:signup' %}">Signup</a>
  				  </li>
  			  {% endif %}
			  {% for provider in providers %}
			  <li class="nav-item active vertical-align">
			    <a href="{% url 'post:oe_haters_list_byprovider' provider_pk=provider.pk %}"><img src="{{ provider.logo.url }}" alt="" class="provider_image navbar_provider_image"></a>
			  </li>
			  {% endfor %}
		    </ul>

		  </div>
		  <form class="form-inline">
			<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
		</form>
		</nav>
		<div class="container full-width">
		{% if messages %}
			{% for message in messages %}
				<div class="alert-message alert
					{% if message.tags == 'info' %}
						alert-info
					{% elif message.tags == 'success' %}
						alert-success
					{% elif message.tags == 'warning' %}
						alert-warning
					{% elif message.tags == 'error' %}
						alert-danger
					{% endif %}
					">{{ message }}</div>
			{% endfor %}
		{% endif %}
			{% block title %}{% endblock %}
			{% block content %}
			{% endblock %}
		</div>
	</body>
</html>