mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('post.urls', namespace='post')),
    url(r'^auth/', include('userauth.urls', namespace='auth')),
]

##여기서부터 튜토리얼 따라가기

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

#django.conf.urls.static.static()함수는
#첫 번째 인자로 주어진 경로(MEDIA_URL)로 요청이 올 경우,
#document_root에 지정된 경로에서 파일을 찾아 응답으로 보내준다.

mysite/post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.post_list, name='post_list'),
    # url(r'^post/(?P<post_pk>\d+)/comment/create/$', views.comment_create, name='comment_create'),
    # url(r'^post/write', views.post_create, name='post_create'),
    # url(r'^post/(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    # url(r'^(?P<post_pk>\d+)/like-toggle/$', views.post_like_toggle, name='post_like_toggle'),
# legacy ends here
    url(r'^oe/list/$', views.oe_haters_list, name='oe_haters_list'),
    url(r'^oe/list/byp/(?P<provider_pk>\d+)/', views.oe_haters_list_byprovider, name='oe_haters_list_byprovider'),
    url(r'^oe/list/bys/$', views.oe_haters_list_byscore, name='oe_haters_list_byscore'),

    url(r'^oe/ranking/(?P<order>\w+)/(?P<page_num>\d+)$', views.oe_haters_ranking, name='oe_haters_ranking'),

    url(r'^oe/(?P<food_pk>\d+)/$', views.oe_haters_detail, name='oe_haters_detail'),
    url(r'^oe/(?P<food_pk>\d+)/hate-toggle/$', views.oe_haters_hate_toggle, name='oe_haters_hate_toggle'),
    url(r'^oe/(?P<food_pk>\d+)/like-toggle/$', views.oe_haters_like_toggle, name='oe_haters_like_toggle'),
    url(r'^oe/(?P<food_pk>\d+)/food/comment/create/$', views.oe_food_comment_create, name='oe_food_comment_create'),
]

mysite/userauth/urls.py
from django.conf.urls import url

from . import views
app_name="member"
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

mysite/templates/haters/oe/detail.html

{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/haters/detail.css' %}?ver=1">
{% endblock %}


{% block content %}

    <div class="container justify-content-center">
        <div class="row justify-content-center">
            <img src="{{ food.provider.logo.url }}" alt="" class="provider_image"><p class="food_name">{{food.name}}</p>
            <img src="{{ food.photo.url }}" alt="" class="food_image">
        </div>
        <div class="displayflex justify-content-center">
            <div class="btn-container">
                <form
                    action="{% url 'post:oe_haters_hate_toggle' food_pk=food.pk %}?next={% url 'post:oe_haters_detail' food_pk=food.pk %}"
                    method="POST"
                    class="form-inline">
                    {% csrf_token %}
                    <button class="btn btn-default btn-post-toggle btnresize btnhate" aria-label="Like button">
                        {% with hate_count=food.hate_foods.count %}
                            <b>싫어요 {{ hate_count }}개</b>
                        {% endwith %}
                    </button>
                </form>
            </div>
            <div class="btn-container">
                <form
                    action="{% url 'post:oe_haters_like_toggle' food_pk=food.pk %}?next={% url 'post:oe_haters_detail' food_pk=food.pk %}"
                    method="POST"
                    class="form-inline">
                    {% csrf_token %}
                    <button class="btn btn-default btn-post-toggle btnresize btnlike" aria-label="Like button">
                        {% with like_count=food.like_foods.count %}
                            <b>좋아요 {{ like_count }}개</b>
                        {% endwith %}
                    </button>
                </form>
            </div>
        </div>


        {% if food.comments_food.exists %}
        <ul class="comment-list">
            {% for comment in food.comments_food.all %}
            <li class="comment">
                <span class="comment-author">{{ comment.author }}</span>
                <span class="comment-content">{{ comment.content }}</span>
            </li>
            {% endfor %}
        </ul>
        <hr>
        {% endif %}
        <form action="{% url 'post:oe_food_comment_create' food_pk=food.pk %}?next={% url 'post:oe_haters_detail' food_pk=food.pk %}" method="POST" class="comment-form">
            {% csrf_token %}
            {{ comment_form.content }}
            <input type="submit" value="게시" >
        </form>


    </div>
{% endblock %}

mysite/templates/haters/oe/main.html

{% extends 'base.html' %}
{% load staticfiles %}
{% load mathfilters %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/haters/style.css' %}?ver=3">
{% endblock %}
{% block navbar %}

{% endblock%}
<!--
<li class="nav-item">
  <a class="nav-link" href="{% url 'member:signup' %}">Signup</a>
</li> -->
{% block content %}
    <div class="container">
		<div class="row">
    {% for food in foods %}
	  <a href="{% url 'post:oe_haters_detail' food_pk=food.pk %}">
		<div class="card col-6 col-lg-3">
		  <img class="card-img-top" src="{{ food.photo.url }}" alt="Card image cap">
		  <div class="card-body">
			<img src="{{ food.provider.logo.url }}" alt="" class="list_provider_image">

			{% if food.score >= 75 %}
			<img src="{% static '52score.png' %}" class="oescore"alt=""><img src="{% static '52score.png' %}" class="oescore"alt=""><img src="{% static '52score.png' %}" class="oescore"alt="">
			{% elif food.score >= 50 %}
		   	<img src="{% static '52score.png' %}" class="oescore"alt=""><img src="{% static '52score.png' %}" class="oescore"alt="">
		    {% elif food.score >= 25 %}
		    <img src="{% static '52score.png' %}" class="oescore"alt="">
		    {% else %}
		    {% endif %}

			<h5 class="card-title">{{food.name}}</h5>
			  <p class="card-text">{% if not food.price %}
				가격 정보없음
			{% else %}
				{{food.price}}원
			{% endif %}
			</p>
		    <a href="#" class=""></a>
		  </div>
		</div>
	  </a>
	{% if forloop.counter|divisibleby:3 %}
	</div>	<div class="row">
  	{% endif %}
    {% endfor %}
    </div>
</div>
{% endblock %}

			<!-- <img src="{{ post.photo.url }}" alt="" class="post-image"> -->

mysite/templates/haters/oe/ranking.html

{% extends 'base.html' %}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/haters/style.css' %}">
{% endblock %}
{% block title %}
오이헤이러스
{% endblock %}


{% block content %}
    {% for provider in providers %}
        <img src="{{ provider.logo.url }}" alt="" class="provider_image">
        <br>
        {{forloop.counter |add:page_num}}{{provider.name}} {{provider.score}}\
    {% endfor %}
{% endblock %}